"""group_olympiads_add_profiles_table

Revision ID: ac5e70cab29c
Revises: f3ddf3a4f48e
Create Date: 2026-06-30 22:39:36.761863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac5e70cab29c"
down_revision: str | Sequence[str] | None = "f3ddf3a4f48e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "olympiad_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("olympiad_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("benefits", sa.JSON(), nullable=True),
        sa.Column("typical_stages", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["olympiad_id"], ["olympiads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("olympiad_id", "slug", name="uq_olympiad_profile"),
    )
    op.drop_column("olympiads", "profiles")
    op.drop_column("olympiads", "typical_stages")
    op.drop_column("olympiads", "level")
    op.drop_column("olympiads", "benefits")
    op.add_column("user_olympiads", sa.Column("profile_slug", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_olympiads", "profile_slug")
    op.add_column("olympiads", sa.Column("benefits", sqlite.JSON(), nullable=True))
    op.add_column("olympiads", sa.Column("level", sa.INTEGER(), nullable=True))
    op.add_column("olympiads", sa.Column("typical_stages", sqlite.JSON(), nullable=True))
    op.add_column("olympiads", sa.Column("profiles", sqlite.JSON(), nullable=True))
    op.drop_table("olympiad_profiles")
    # ### end Alembic commands ###
